spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ff?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456789
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true

rpc:
  host:
    127.0.0.1
  port:
    67